apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/janne6565/holiday-dashboard-backend:placeholder
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          envFrom:
            - secretRef:
                name: backend-secrets
          startupProbe:
            httpGet:
              path: /actuator/health
              port: management
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: management
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: management
            periodSeconds: 15
