apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: holidash-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - holiday.jannekeipert.de
      secretName: prod-tls
  rules:
    - host: holiday.jannekeipert.de
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
